version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build and Test
          command: mvn -B verify
      - store_test_results:
          path: target/report
      - store_artifacts:
          path: target/report
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/